#!/usr/bin/env bash

set -e

if [ -z "$ANDROID_SERIAL" ]; then
    echo "error: \$ANDROID_SERIAL not defined"
    exit -1
fi

adb connect "$ANDROID_SERIAL"
gradle installDebug
adb shell am start -n com.kotfind.android_course/.MainActivity
